sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: P6P4LwJ0Pnsld8+cuvEBmS9rP7yEAqlDfdth6ZM0oldTK9s36De4Gf2e383U6MyQuPYYnqSvf61JJ/eXrt9m6JYUWU9niyEf6JqKCBMPT/tSxjJEOaw2oYgWqUfd9AUFF1ORPLWcr26G5kNm59P9YLnlhT+f0zd/4mJH+zJpIpXsydo9g34na810DbA/GacyIkNCmdNnJPq4+ACiHXRVPjM0JW7EWdk5cGef0ntuaVcWJBdDboSrZ1VzID+uCRb2r4Ijv1vyyxUx8s0VCZr8UtIpUjMc8K1rseqvdYvgF+lDTR5ZALTbU0WXoEEhCg2+UzMV0vSMD66yzEXI1T5pJlIZPQztKmTI2x1P/LRfN2JBv19XVr5aZE8rtelCR5eWM7f8y52apSVF4cWCOgNz9YoX9HObYwmZg1dXUtcetIWunRTr9siB7KIuW773bfzTtRU78sbYggQFudBF+mhPdaimK7EsQpQiugp1ZcO3E4TQrYjO4OitCmh4hqZ/WUiTSTxBA5zpato/oK1XFQEDAhGAnn07RdaSF4OOiI63lrfKCH0npu26V4bkRhUVGo/2ryxNemNHd9FPHRkBG2+hntQEfAR1+axVgBaF20cdMNErMUc4yPx1bbPhKz6sgqrLjsCFh80SwT0UMKncD1ZFUSUbQ+mVbtSI8JWbuw/Kywg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Heroic-Romances-of-Ireland-Translated-into-English-Prose-and-Verse-Complete_5680
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy